# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default='No Bio Provided'),
        ),
    ]
