# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user_id',
            new_name='user',
        ),
    ]
