# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20170426_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='base_user',
        ),
        migrations.AddField(
            model_name='tutor',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
