# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tutor', '0003_auto_20170427_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(to='courses.Courses'),
        ),
    ]
