# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_text',
            field=models.TextField(default='No Search Given'),
        ),
    ]
