# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170508_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default="No City Provided"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(default="USA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street_address_1',
            field=models.TextField(default="No Address Provided"),
            preserve_default=False,
        ),
    ]
