# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170511_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
    ]
