# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170511_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.TextField(),
        ),
    ]
