# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('users', '0008_auto_20170511_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
    ]
