# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0002_auto_20170517_1613'),
        ('users', '0009_user_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ManyToManyField(null=True, to='schedule.Schedule'),
        ),
    ]
