# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_ram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ram_id',
            field=models.TextField(default='R00000000'),
        ),
    ]
