# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20170427_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_base',
            new_name='user',
        ),
    ]
