# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170427_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
