# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20170428_0623'),
        ('student', '0007_student_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLikes',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.Student')),
                ('liked_tutors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Tutor')),
            ],
            bases=('student.student',),
        ),
    ]
