# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=0)),
                ('tuesday', models.BooleanField(default=0)),
                ('wednesday', models.BooleanField(default=0)),
                ('thursday', models.BooleanField(default=0)),
                ('friday', models.BooleanField(default=0)),
                ('saturday', models.BooleanField(default=0)),
                ('sunday', models.BooleanField(default=0)),
            ],
        ),
    ]
