# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.TextField(default=''),
        ),
    ]
