# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170511_0451'),
        ('chat', '0004_auto_20170511_0443'),
    ]

    operations = [
    ]
