# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 15:23
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0014_auto_20170515_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='initiator_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 23, 20, 182913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='recipient_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 23, 20, 182967, tzinfo=utc)),
        ),
    ]
