# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:13
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0015_auto_20170516_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='initiator_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 16, 13, 24, 46726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='recipient_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 16, 13, 24, 46779, tzinfo=utc)),
        ),
    ]
