# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:33
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0016_auto_20170517_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='initiator_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 16, 33, 9, 397031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='recipient_last_read_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 16, 33, 9, 397086, tzinfo=utc)),
        ),
    ]
